esn_model:
  num_unit: 500 
  w_in_dist: [-1.0,1.0]
  seed: 123 
  w_internal_dist: [-1.0,1.0]
  nu_dist: [0.0,0.0]
  zero_density: 0.05

environment:
  # name: CartPole-v0
  name: Acrobot-v1
  t_max: 500

cma_es:
  max_num_gen: 10 
  population_size: 1000 
  sigma: 1.5

# hydra setting
hydra:
  run:
    dir: esn_${environment.name}
